### ISSUE TITLE
Incorrect entries

### ISSUE THREAD

**Issue by oParoxysm** [chmey/py-iptoasn#3]
Hello,

Is there an updated or correct database? When resolving 1.1.1.1, I get another ASN other than cloudflare. Assuming an very common entry like that is incorrect, I can only assume other data in the file is also invalid.

Thanks

**Comment by chmey** [comment]
Hi, thanks for your interest.

I could verify as well that with by launching the script which downloads the newest database from https://iptoasn.com/ . The IP 1.1.1.1 then evaluates to:

```
curl localhost:8080/api/ip/1.1.1.1
{"ip": "1.1.1.1", "as_number": 38726, "as_country_code": "VN", "as_description": "VTCDIGICOM-AS-VN VTC DIGICOM", "range_start": "1.1.1.0", "range_end": "1.1.1.3"}
``` 

I verified it using another ASN lookup online: https://hackertarget.com/as-ip-lookup/ and it returns the same result.

--- 

So the application is behaving as intended and the linked ASN by iptoasn.com for that IP address has changed since writing the README file.
